// react-memory-game/src/App.js
import React, { Component } from 'react';
import Dashboard from './components/dashboard/Dashboard'
import Chessboard from './components/chessboard/Chessboard'
import PlayStatus from './components/play_status/PlayStatus'

import './App.css';

class App extends Component {
  render() {
    return (
      <div className="game-panel"
        onDragStart={(e) => { e.preventDefault() }}
        onContextMenu={(e) => { e.preventDefault() }}
      >
        <Dashboard/>
        <Chessboard/>
        <PlayStatus/>
      </div>
    )
  }
}

export default App

// vue-memory-game/src/App.vue
<template>
  <div class="game-panel"
    ondragstart="return false;"
    oncontextmenu="return false;"
    onselectstart="return false;"
    onselect="document.selection.empty();"
  >
    <dashboard></dashboard>
    <chessboard></chessboard>
    <play-status></play-status>
  </div>
</template>

<script>
import Dashboard from './components/Dashboard'
import Chessboard from './components/Chessboard'
import PlayStatus from './components/PlayStatus'
export default {
  components: {
    Dashboard,
    Chessboard,
    PlayStatus
  },
  methods: {}
}
</script>
