// vue-memory-game/src/components/PlayStatus.vue
<template>
  <div class="status-footer">
    <span>Level {{level}}</span>
    <span class="play-status" v-if="status === types.READY">Ready</span>
    <span class="play-status" v-if="status === types.PLAYING" >Playing</span>
    <span class="play-status pass" v-if="status === types.PASS" @click="reset">Play again</span>
    <span> {{elapsed}} s</span>
  </div>
</template>

<script>
import * as types from './../constant'
import { mapState, mapActions } from 'vuex'
export default {
  data () {
    return {
      types
    }
  },
  computed: {
    ...mapState(['elapsed', 'level', 'status'])
  },
  methods: {
    ...mapActions({
      reset: types.RESET
    })
  }
}
</script>

<style>

</style>

// react-memory-game/src/components/play_status/PlayStatus.js
import React, { Component } from 'react'

class PlayStatus extends Component {
  constructor(props) {
    super(props)
    this.state = {
      elapsed: 0,
      level: 1
    }
  }
  render() {
    return (
      <div className="status-footer">
        <span>Level {this.state.level}</span>
        { this.StatusRender() }
        <span> {this.state.elapsed} s</span>
      </div>
    )
  }
  StatusRender() {
    const status = 'playing'
    if (status === 'ready') {
      return (<span className="play-status">Ready</span>)
    }
    if (status === 'playing') {
      return (<span className="play-status">Playing</span>)
    }
    if (status === 'pass'){
      return (<span className="play-status pass">Play again</span>)
    }
  }
}

export default PlayStatus
